# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 19:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import dynamics.models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_dimension_x', models.IntegerField(default=3)),
                ('box_dimension_y', models.IntegerField(default=3)),
                ('box_dimension_z', models.IntegerField(default=3)),
                ('box_coordinate_x', models.IntegerField(default=0)),
                ('box_coordinate_y', models.IntegerField(default=0)),
                ('box_coordinate_z', models.IntegerField(default=0)),
                ('probe', multiselectfield.db.fields.MultiSelectField(choices=[('COO-', 'COO-'), ('NH3+', 'NH3+'), ('CH3-', 'CH3-'), ('Ar(C-H)', 'Ar(C-H)'), ('O-H', 'O-H'), ('NH2', 'NH2'), ('Ar(N-H)', 'Ar(N-H)'), ('C=O', 'C=O'), ('NH2(ARG)', 'NH2(ARG)'), ('(H2O)HO', '(H2O)HO'), ('Zn2+', 'Zn2+'), ('Cl-', 'Cl-'), ('Na+', 'Na+')], max_length=72)),
            ],
        ),
        migrations.CreateModel(
            name='Dynamic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_size', models.IntegerField(default=10)),
                ('number_of_molecules', models.IntegerField()),
                ('number_of_atoms_for_alignment', models.IntegerField()),
                ('configured', models.BooleanField(default=False)),
                ('process_finished', models.BooleanField(default=False)),
                ('email_sent', models.BooleanField(default=False)),
                ('run_dynamics', models.BooleanField(default=True)),
                ('run_alignment', models.BooleanField(default=False)),
                ('run_lqtagrid', models.BooleanField(default=False)),
                ('started', models.DateField(auto_now_add=True)),
                ('lqtagrid_box', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dynamics.Box')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Molecule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=dynamics.models.path_builder)),
                ('atoms', models.CharField(max_length=100)),
                ('reference', models.BooleanField(default=False)),
                ('dynamic_executed', models.BooleanField(default=False)),
                ('alignment_executed', models.BooleanField(default=False)),
                ('lqtagrid_executed', models.BooleanField(default=False)),
                ('dynamic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamics.Dynamic')),
            ],
        ),
    ]
