# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='box_dimension_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='box',
            name='box_dimension_y',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='box',
            name='box_dimension_z',
            field=models.IntegerField(default=0),
        ),
    ]
