# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamics', '0002_auto_20170113_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='step',
            field=models.FloatField(default=1.0),
        ),
    ]
